### ISSUE TITLE
Doesn't work with some things

### ISSUE THREAD

**Issue by Paradox75831004** [SylviBlossom/LC-TerminalConflictFix#1]
Assembly Code: 018dc2ff-ad61-2377-998d-03dcecd5a835

For example, with these things and other mods, this mod does not help much. If you could improve it somehow, I would be happy. (Similar bug with "Helmet")

If I try to buy Emergency Die, he says I want to buy ammo...
![image](https://github.com/SylviBlossom/LC-TerminalConflictFix/assets/72872478/90f4ea3d-99e9-4d6a-9603-09cb21c03869)
![image](https://github.com/SylviBlossom/LC-TerminalConflictFix/assets/72872478/a4ed3dbc-3745-46db-9471-2acf7ea850a7)

**Comment by SylviBlossom** [comment]
thanks for the report! there was a small issue preventing this from working and the fix will be on the thunderstore shortly, but keep note that spaces in the terminal are separate "arguments", such as buying a different number of items. for things that share a first word you need to type more of the name without a space - e.g. "emergencyd" for the Emergency Die
