### ISSUE TITLE
Incompatible with StockOverview

### ISSUE THREAD

**Issue by Fl4sHNoX** [SylviBlossom/LC-TerminalConflictFix#2]
The "stock" command added by the [StockOverview](https://github.com/Squall4120/StockOverview) mod redirects to the Moons screen of the terminal instead of showing the stock, the log console seems to indicate it may be related to an issue TerminalConflictFix:

https://github.com/SylviBlossom/LC-TerminalConflictFix/assets/3759901/851c7198-c3c8-4660-80d2-67cc9da06522

**Comment by SylviBlossom** [comment]
these mods seem to work together on their own, though in my testing it doesnt even print anything from this mod to the console - there must be some other mod causing that, i see you posted your modlist so ill check incompatibilies with other terminal-related mods there

**Comment by SylviBlossom** [comment]
this seems to be purely a LethalLevelLoader issue, which also happens with vanilla commands: https://github.com/IAmBatby/LethalLevelLoader/issues/54
